# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Swift Style Guidelines
description: >- # this means to ignore newlines until "baseurl:"
  A comprehensive set of Swift language style guidelines
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Swift-Style-Guidelines.BHStudios.org" # the base hostname & protocol for your site, e.g. http://example.com
author:
    name: Blue Husky Studios
    email: Webmaster@BHStudios.org

oss:
    history-url-root: https://github.com/BlueHuskyStudios/Swift-Style-Guidelines/commits/master/
    history-url-suffix:
    edit-url-root: https://github.com/BenLeggiero/blog/edit/master/
    edit-url-suffix:
    create-new-issue-url: https://github.com/BlueHuskyStudios/Swift-Style-Guidelines/issues/new

sidebar:
    header-background-relative-url: /Images/Social/Social-Preview.png

# Build settings
markdown: kramdown
# theme: neon
plugins:
  - jekyll-feed
sass:
    style: expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: true  # true|false
        # If true, compiles sass directly into your jekyll source directory
        # As well as your destination directory
    load_paths:
        - assets
    sass_dir: assets
kramdown:
    parse_block_html: true



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
